embed_assets: off
compress_assets: off

javascripts:
  mksoft:
    - public/libs/jquery.js
    - public/libs/prefixfree.js
    - public/libs/prefixfree.jquery.js
    - public/scripts/app.js
    - public/scripts/trig/util.js
    - public/scripts/world/earth.js
    - public/scripts/world/sun.js
    - public/scripts/world/ray.js
    - public/scripts/world/sea.js
    - public/scripts/world/wave.js
    - public/scripts/world/sky.js
    - public/scripts/world/cloud.js

stylesheets:
  mksoft:
    - public/styles/**/*.css
