embed_assets: off
compress_assets: off

javascripts:
  mksoft:
    - public/libs/jquery.js
    - public/scripts/app.js
    - public/scripts/world/world.js
    - public/scripts/world/sea.js
    - public/scripts/world/wave.js
    - public/scripts/world/sky.js
    - public/scripts/world/cloud.js

stylesheets:
  mksoft:
    - public/styles/**/*.css
